version: "3.7"

services:
    render:
        build:
            context: .
            args:
                arg_port: 5000
        ports:
            - "8003:5000"
        volumes:
            - "./src/:/app/"
        tty: true # bind console
