version: '3'

services:
    rest:
        build: ./http_server/
        ports:
            - "8000:5000"
        env_file:
            - ./.env
            - ./http_server/.env
        # restart: unless-stopped

    # socket:
    #     build:
    #         context: .
    #         dockerfile: ./websocket_server/
    #     ports:
    #         - "8001:5001"
    #     env_file:
    #         - ./.env
    #         - ./websocket_server/.env
    #     links:
    #         - render

    render:
        build:
            context: .
            dockerfile: ./render_server/
        ports:
            - "80:80"
            - "433:433"
        # volumes:
        #     - ":"
        # depends_on:
        #     - socket
