version: "3.7"

services:
    # front:
    #     build:
    #         context: ./front_builder/
    #         dockerfile: Dockerfile.prod
    #         args:
    #             arg_port: 5000
    #     ports:
    #         - "80:5000" # http
    #         - "443:5000" # https
    #     # restart: always

    rest:
        build:
            context: ./http_server/
            dockerfile: Dockerfile.prod
            args:
                arg_port: 5000
        ports:
            - "8001:5000"
        env_file:
            - ./.env
        tty: true # bind console
        restart: always

    socket:
        build:
            context: ./websocket_server/
            dockerfile: Dockerfile.prod
            args:
                arg_port: 5000
        ports:
            - "8002:5000"
        env_file:
            - ./.env
        tty: true # bind console
        restart: always

    render:
        build:
            context: ./render_server/
            dockerfile: Dockerfile.prod
            args:
                arg_port: 5000
        ports:
            - "8003:5000"
        tty: true # bind console
        restart: always
        depends_on:
            - socket
