version: "3.7"

services:
    rest:
        build: 
            context: .
            args:
                arg_port: 5000
        ports:
            - "8001:5000"
        env_file:
            - ./../.env
        volumes:
            - "./src/:/src/"
            - "./credentials/:/credentials/"
        tty: true # bind console
        restart: on-failure
