version: "3.7"

services:
    socket:
        build:
            context: .
            args:
                arg_port: 5000
        ports:
            - "8002:5000"
        env_file:
            - ./../.env
        volumes:
            - "./src/:/src/"
            - "./cpp/:/src/brique2/cpp/"
        tty: true # bind console
