version: "3.7"

services:
    front:
        build:
            context: .
            args:
                arg_port: 5000
        ports:
            - 3001:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
        # volumes: # quand sera prêt, montage des fichiers de code comme volume et prise en compte des modifs à chaud
        #     - '.:/app'
        #     - '/app/node_modules'
        tty: true # bind console
